objects/Machine_Fixture__c.object
<CustomObject><fields>
        <fullName>Product_Configuration__c</fullName>
        <label>Product Configuration</label>
        <referenceTo>Product_Configuration__c</referenceTo>
        <relationshipLabel>Machine Fixtures</relationshipLabel>
        <relationshipName>Machine_Fixtures</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>false</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Machine Fixture</label><nameField>
        <displayFormat>MachFix-{000000}</displayFormat>
        <label>Machine Fixture Number</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Machine Fixtures</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Material__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Material</label><nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Materials</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Pattern__c.object
<CustomObject><fields>
        <fullName>Product_Configuration__c</fullName>
        <label>Product Configuration</label>
        <referenceTo>Product_Configuration__c</referenceTo>
        <relationshipLabel>Patterns</relationshipLabel>
        <relationshipName>Patterns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>false</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Pattern</label><nameField>
        <displayFormat>Pattern-{000000}</displayFormat>
        <label>Pattern Number</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Patterns</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Process__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Process</label><nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Processes</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Product_Configuration__c.object
<CustomObject><fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Price__c</fullName>
        <label>Selling Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>WI Quote</label><nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField><pluralLabel>WI Quotes</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Product_Material__c.object
<CustomObject><fields>
        <fullName>Material__c</fullName>
        <label>Material</label>
        <referenceTo>Material__c</referenceTo>
        <relationshipLabel>Product Materials</relationshipLabel>
        <relationshipName>Product_Materials_del</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Product_Configuration__c</fullName>
        <label>Product Configuration</label>
        <referenceTo>Product_Configuration__c</referenceTo>
        <relationshipLabel>Product Materials</relationshipLabel>
        <relationshipName>Product_Materials</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Product Material</label><nameField>
        <label>Product Materials Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Product Materials</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Product_Process__c.object
<CustomObject><fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Product Processes</relationshipLabel>
        <relationshipName>Product_Processes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Product_Configuration__c</fullName>
        <label>Product Configuration</label>
        <referenceTo>Product_Configuration__c</referenceTo>
        <relationshipLabel>Product Processes</relationshipLabel>
        <relationshipName>Product_Processes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Product Process</label><nameField>
        <label>Product Process Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Product Processes</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Product_Service__c.object
<CustomObject><fields>
        <fullName>Product_Configuration__c</fullName>
        <label>Product Configuration</label>
        <referenceTo>Product_Configuration__c</referenceTo>
        <relationshipLabel>Product Services</relationshipLabel>
        <relationshipName>Product_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Product Services</relationshipLabel>
        <relationshipName>Product_Services</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>false</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Product Service</label><nameField>
        <displayFormat>ProdServ-{000000}</displayFormat>
        <label>Product Service Number</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Product Services</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Service__c.object
<CustomObject><fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Service</label><nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Services</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/CloneProductConfigurationTest.cls
/*
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Test class for CloneProductConfiguration
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Initial implementation
* @author		Lucian Ciobanu <lucian.ciobanu@deutoria.com>
* @created		2017-02-10
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Changes
*
*
* ─────────────────────────────────────────────────────────────────────────────────────────────────
*/
@isTest
public class CloneProductConfigurationTest {

    public static testMethod void TestClone() {
        
        // Setup data
        Account acc = new Account(Name = 'testAcc');
        insert acc;
        Opportunity opp = new Opportunity(Name = 'testOpp', Account = acc , CloseDate = date.valueOf('2017-10-10') , StageName = 'Collect Information');
        insert opp;
		Product_Configuration__c prodConfig = new Product_Configuration__c(Name = 'testProd', Opportunity__c = opp.Id, Price__c = 12);
        insert prodConfig;
        Material__c m = new Material__c();
        insert m;
        Product_Material__c mat = new Product_Material__c(Product_Configuration__c = prodConfig.Id, Material__c = m.Id);
        insert mat;
        Process__c p = new Process__c();
        insert p;
        Product_Process__c proc = new Product_Process__c(Product_Configuration__c = prodConfig.Id, Process__c = p.Id);
        insert proc;
        Pattern__c patt = new Pattern__c(Product_Configuration__c = prodConfig.Id);
        insert patt;
        Machine_Fixture__c fix = new Machine_Fixture__c(Product_Configuration__c = prodConfig.Id);
        insert fix;
        Service__c s = new Service__c();
        insert s;
        Product_Service__c serv = new Product_Service__c(Product_Configuration__c = prodConfig.Id, Service__c = s.Id);
        insert serv;
        
        
        // Run the code
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(prodConfig);
        CloneProductConfiguration ctrl = new CloneProductConfiguration(sc);
        ctrl.clone.Name = 'testProd2';
        ctrl.CloneRecord();
        ctrl.GoBack();
        Test.stopTest();
        
        // Verify results
        System.assertEquals(2, [SELECT COUNT() FROM Product_Configuration__c]);
        System.assertEquals(2, [SELECT COUNT() FROM Product_Material__c]);
        System.assertEquals(2, [SELECT COUNT() FROM Product_Process__c]);
        System.assertEquals(2, [SELECT COUNT() FROM Pattern__c]);
        System.assertEquals(2, [SELECT COUNT() FROM Machine_Fixture__c]);
        System.assertEquals(2, [SELECT COUNT() FROM Product_Service__c]);
    }
    
}