objects/Opportunity.object
<CustomObject><fields>
        <fullName>Synced_Product_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Synced Product Quote</label>
        <referenceTo>Product_Configuration__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>false</enableHistory><sharingModel>Read</sharingModel></CustomObject>

objects/Product_Configuration__c.object
<CustomObject><fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Order_Qty__c</fullName>
        <label>Order Qty</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Price__c</fullName>
        <label>Selling Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>WI Quote</label><nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField><pluralLabel>WI Quotes</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/SyncOppExtensionTestClass.cls
/*
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Test class for SyncOppExtension
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Initial implementation
* @author		Lucian Ciobanu <lucian.ciobanu@deutoria.com>
* @created		2017-02-08
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Changes
*
*
* ─────────────────────────────────────────────────────────────────────────────────────────────────
*/
@isTest
public class SyncOppExtensionTestClass {
    
    @isTest
    private static void TestSyncOppValid(){
        
        // Setup data
        Account acc = new Account(Name = 'testAcc');
        insert acc;
        Opportunity opp = new Opportunity(Name = 'testOpp', Account = acc , CloseDate = date.valueOf('2017-10-10') , StageName = 'Collect Information');
        insert opp;
		Product_Configuration__c prodConfig = new Product_Configuration__c(Name = 'testProd', Opportunity__c = opp.Id, Price__c = 12, Order_Qty__c = 1);
        insert prodConfig;
        ApexPages.StandardController sc = new ApexPages.StandardController(prodConfig);
        SyncOppExtension syncOpp = new SyncOppExtension(sc);
        
        // Run the code
        Test.startTest();
        PageReference pageRef = syncOpp.Sync();
        Test.stopTest();
        
        // Verify results
        opp = [SELECT Id, Synced_Product_Quote__c, Amount FROM Opportunity LIMIT 1];
        System.assertEquals(prodConfig.Id, opp.Synced_Product_Quote__c);
        System.assertEquals(12, opp.Amount);
        
    }
    
    @isTest
    private static void TestSyncOppValid2(){
        
        // Setup data
        Account acc = new Account(Name = 'testAcc');
        insert acc;
        Opportunity opp = new Opportunity(Name = 'testOpp', Account = acc , CloseDate = date.valueOf('2017-10-10') , StageName = 'Collect Information');
        insert opp;
		Product_Configuration__c prodConfig = new Product_Configuration__c(Name = 'testProd', Opportunity__c = opp.Id, Price__c = 12, Order_Qty__c = 1);
        insert prodConfig;
        ApexPages.StandardController sc = new ApexPages.StandardController(prodConfig);
        SyncOppExtension syncOpp = new SyncOppExtension(sc);
        
        // Run the code
        Test.startTest();
        PageReference pageRef = syncOpp.GoBack();        
        Test.stopTest();

        // Verify results
        System.assertEquals('/' + prodConfig.Id, pageRef.getUrl());
        
    }
    
    @isTest
    private static void TestSyncOppInvalid1(){
		
        // Setup data
        Product_Configuration__c prodConfig = new Product_Configuration__c();
        ApexPages.StandardController sc = new ApexPages.StandardController(prodConfig);
        SyncOppExtension syncOpp = new SyncOppExtension(sc);
        
        // Run the code
        Test.startTest();
        PageReference pageRef = syncOpp.Sync();
        syncOpp.GoBack();
        Test.stopTest();
        
		// Verify results
        System.assertEquals(null, pageRef);
        
    }
    
    @isTest
    private static void TestSyncOppInvalid2(){
		
        // Setup data
        Account acc = new Account(Name = 'testAcc');
        insert acc;
        Opportunity opp = new Opportunity(Name = 'testOpp', Account = acc , CloseDate = date.valueOf('2017-10-10') , StageName = 'Collect Information');
        insert opp;
		Product_Configuration__c prodConfig = new Product_Configuration__c(Name = 'testProd', Price__c = 12, Order_Qty__c = 1);
        insert prodConfig;
        ApexPages.StandardController sc = new ApexPages.StandardController(prodConfig);
        SyncOppExtension syncOpp = new SyncOppExtension(sc);
        
        // Run the code
        Test.startTest();
        PageReference pageRef = syncOpp.Sync();
        syncOpp.GoBack();
        Test.stopTest();
        
        // Verify results
        System.assertEquals(null, pageRef);        
    }

}