objects/Process__c.object
<CustomObject><fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Synchro_Index__c</fullName>
        <externalId>true</externalId>
        <label>Synchro Index</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Process</label><nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Processes</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/SQLSyncProcessesTest.cls
/*
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Test class for SQLSyncProcess / SQLSyncBase
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Initial implementation
* @author		Lucian Ciobanu <lucian@cloudmineconsulting.com>
* @created		2017-03-31
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Changes
*
*
* ─────────────────────────────────────────────────────────────────────────────────────────────────
*/
@isTest
public class SQLSyncProcessesTest {

    public static testMethod void TestSync() {
        
        // Setup data
        Process__c p1 = new Process__c();
        p1.Name = 'Process298461';
        p1.Synchro_Index__c = 1;
        insert p1;
        
        Test.setMock(WebServiceMock.class, new SQLSyncProcessesMock());
        
        // Run the code
        Test.startTest();
        SQLSyncProcess ctrl = new SQLSyncProcess();
        ctrl.execute(null);
        Test.stopTest();
        
        // Verify results
        p1 = [SELECT Description__c FROM Process__c WHERE Id = :p1.Id];
        Process__c p2 = [SELECT Description__c FROM Process__c WHERE Id != :p1.Id LIMIT 1];
        System.assertEquals('Description1', p1.Description__c);
        System.assertEquals('Description2', p2.Description__c);
    }

}