objects/Product_Category__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Product Category</label><nameField>
        <label>Product Category Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Product Categories</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Product_Configuration__c.object
<CustomObject><fields>
        <fullName>Actual_Product_Category_Cost__c</fullName>
        <label>Actual Product Category Cost</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Net_Wt__c</fullName>
        <label>Net Weight (KG)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Product_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Category</label>
        <referenceTo>Product_Category__c</referenceTo>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Yield__c</fullName>
        <label>Yield</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>WI Quote</label><nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField><pluralLabel>WI Quotes</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/Product_Config_Trigger_Handlers.cls
/*
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Handler Class for Product Configuration Triggers --- Mainly used for Metal Yield/Price calculations
* covered by Product_Config_Triggers_Test
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Initial implementation
* @author       Jason Sun (jason@cloudmineconsulting.com)
* @created      2017-02-10
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Changes
* ─────────────────────────────────────────────────────────────────────────────────────────────────
*/
public class Product_Config_Trigger_Handlers {

    private static Set<Id> processedProdConfigIds = new Set<Id>();
    
    public static void beforeInsertHandler(List<Product_Configuration__c> newProdConfigList){
        List<Product_Configuration__c> prodConfigsToProcess = new List<Product_Configuration__c>();
        
        for(Product_Configuration__c pc: newProdConfigList){
            if(!processedProdConfigIds.contains(pc.Id) && pc.Product_Category__c != NULL ){
                prodConfigsToProcess.add(pc);
            }
        }
        if(!prodConfigsToProcess.isEmpty()){
            calcMetalPriceandUpdate(prodConfigsToProcess);
        }
    }
    
    public static void beforeUpdateHandler(Map<Id,Product_Configuration__c> newProdConfigMap, Map<Id,Product_Configuration__c> oldProdConfigMap){
        List<Product_Configuration__c> prodConfigsToProcess = new List<Product_Configuration__c>();
        
        for(Product_Configuration__c pc: newProdConfigMap.values()){
            if(!processedProdConfigIds.contains(pc.Id) && pc.Product_Category__c != NULL &&
              (pc.Product_Category__c != oldProdConfigMap.get(pc.Id).Product_Category__c ||
               pc.Yield__c != oldProdConfigMap.get(pc.Id).Yield__c ||
               pc.Net_Wt__c != oldProdConfigMap.get(pc.Id).Net_Wt__c) ){
                prodConfigsToProcess.add(pc);
            }
        }
        if(!prodConfigsToProcess.isEmpty()){
            calcMetalPriceandUpdate(prodConfigsToProcess);
        }        
    } 
    
    private static void calcMetalPriceandUpdate(List<Product_Configuration__c> prodConfigList){
        for(Product_Configuration__c pc: prodConfigList){
            if(pc.Yield__c != NULL && pc.Net_Wt__c != NULL){
                Metal_Rates_Utility utility = new Metal_Rates_Utility(pc.Product_Category__c);
                pc.Actual_Product_Category_Cost__c = utility.getMetalPrice(pc.Yield__c, pc.Net_Wt__c);
            }
        }
    }

    
}