objects/Product_Category__c.object
<CustomObject><fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Synchro_Index__c</fullName>
        <externalId>true</externalId>
        <label>Synchro Index</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Product Category</label><nameField>
        <label>Product Category Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Product Categories</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/SQLSyncProductCategoryTest.cls
/*
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Test class for SQLSyncProductCategory / SQLSyncBase
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Initial implementation
* @author		Lucian Ciobanu <lucian@cloudmineconsulting.com>
* @created		2017-04-11
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Changes
*
*
* ─────────────────────────────────────────────────────────────────────────────────────────────────
*/
@isTest
public class SQLSyncProductCategoryTest {

    public static testMethod void TestSync() {
        
        // Setup data
        Product_Category__c m1 = new Product_Category__c();
        m1.Name = 'Service298461';
        m1.Synchro_Index__c = 1;
        insert m1;
        
        Test.setMock(WebServiceMock.class, new SQLSyncProductCategoryMock());
        
        // Run the code
        Test.startTest();
        SQLSyncProductCategory ctrl = new SQLSyncProductCategory();
        ctrl.execute(null);
        Test.stopTest();
        
        // Verify results
        m1 = [SELECT Description__c FROM Product_Category__c WHERE Id = :m1.Id];
        Product_Category__c m2 = [SELECT Description__c FROM Product_Category__c WHERE Id != :m1.Id LIMIT 1];
        System.assertEquals('100', m1.Description__c);
        System.assertEquals('200', m2.Description__c);
    }
    
}